# Book settings
title                       : Pythonize Data Crunching and Visualization  # The title of the book. Will be placed in the left navbar.
author                      : Zhiyao Yin  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : ""  # A path to the book logo
#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)

repository:
  url                       : https://github.com/chuckedfromspace/pythonize  # The URL to your book's repository
  path_to_book              : "pythonize"  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links
html:
  use_repository_button     : true
  use_issues_button         : true
  use_edit_page_button      : true

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  extra_extensions:
    - sphinx_panels
    - sphinx_click.ext
    - sphinx_inline_tabs
